config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/login'

  post 'users/register'

  post 'users/profile'

  root 'users#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to(:user)
end

app/models/user.rb
class User < ApplicationRecord
  has_many(:phones)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def register
    @user = User.new
    @user.fullname = params[:fullname]
    @user.username = params[:username]
    @user.password = params[:password]
    @user.email = params[:email]
    @user.street = params[:street]
    @user.city = params[:city]
    @user.state = params[:state]
    @user.postalcode = params[:postalcode]
    @user.country = params[:country]
    @user.homephone = params[:phone_number_home]
    @user.cellphone = params[:phone_number_cell]
    @user.workphone = params[:phone_number_work]


    if @user.save
      cookies[:user_id] = @user.id
    else
      render plain: 'Could not save user'
    end
  end

  def login; end

  def profile
    @user = User.find_by(username: params[:username],
                         password: params[:password])

    if @user
      flash.now[:success] = 'Logged in!'
    else
      flash.now[:error] = 'Invalid Credentials'
      render 'login'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :username, :password, :fullname, :street,
      :city, :state, :postalcode, :country, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RegistrationApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flash-container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%=message_type %>">
          <%= message %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Registration Form</h1>

<form action="users/register" method="POST">
  <p><input type="text" name="fullname" placeholder="Full name" autofocus required/></p>
  <p><input type="text" name="username" placeholder="Your username"  required/></p>
  <p><input type="password" name="password" placeholder="Your password" required/></p>
  <p><input type="email" name="email" placeholder="Your email" required/></p>
  <p><input type="text" name="street" placeholder="Street" required/></p>
  <p><input type="text" name="city" placeholder="City" required/></p>
  <p><input type="text" name="state" placeholder="State" required/></p>
  <p><input type="text" name="postalcode" placeholder="Postal Code" required/></p>
  <p><input type="text" name="country" placeholder="Country" required/></p>
  <p><input type="text" name="phone_number_home" placeholder="Home Phone Number" /></p>
  <p><input type="text" name="phone_number_cell" placeholder="Cell Phone Number" /></p>
  <p><input type="text" name="phone_number_work" placeholder="Work Phone Number" /></p>

  <input type="submit" value="Register" />
</form>

<p>
  Already registered? <%= link_to "Login", users_login_path %>
</p>

app/views/users/login.html.erb
<h1>Login Form</h1>

<form action="profile" method="POST">
  <input type="text" name="username" placeholder="Your username" autofocus required/>
  <input type="password" name="password" placeholder="Your password" required/>

  <input type="submit" value="Login" />
</form>

app/views/users/profile.html.erb
<h1>Your Information</h1>

<table>
  <tr>
    <td>
      Username:
    </td>
    <td>
      <%= @user.username %>
    </td>
  </tr>
  <tr>
    <td>
      Email:
    </td>
    <td>
      <%= @user.email %>
    </td>
  </tr>
  <tr>
    <td>
      Full name:
    </td>
    <td>
      <%= @user.fullname %>
    </td>
  </tr>
  <tr>
    <td>
      Address:
    </td>
    <td>
      <%= @user.street %> <%= @user.city %> <%= @user.state %> <%= @user.postalcode %>
    </td>
  </tr>
  <tr>
    <td>
      Country:
    </td>
    <td>
      <%= @user.country %>
    </td>
  </tr>
  <tr>
    <td>
      Phone:
    </td>
    <td>
      <%= @user.phone_number %>
    </td>
  </tr>
</table>

app/views/users/register.html.erb
<h1>Welcome</h1>
<p>Thanks for registering, <%= @user.username %>!</p>

<%= link_to "Login", users_login_path %>